### ISSUE TITLE
🐛 Bug Report: Missing Restart Policy for bpkilint Service in docker-compose.yml

### ISSUE THREAD

**Issue by jidehem92** [hakwerk/labca#162]
## Description
The `bpkilint` service in the `docker-compose.yml` file of the LabCA project lacks a restart policy. This can lead to the container remaining in an 'Exited' state if it is stopped due to server reboots, Docker updates, or resource constraints. As a result, dependent services such as `labca-boulder-1` may fail to start properly, causing a `502 Bad Gateway` error when accessing `/directory` via the LabCA Nginx proxy.

## 🔍 Steps to Reproduce
1. Start LabCA using the provided `docker-compose.yml`.
2. Stop the `bpkilint` container manually using:
   ```sh
   docker stop labca-bpkilint-1
   ```
3. Check the container status with:
   ```sh
   docker ps -a | grep labca-bpkilint-1
   ```
4. Notice that the container remains in an **Exited** state.
5. Attempt to access the Boulder directory via Nginx (`https://lxc-labca.localdomain/directory`).
6. A **502 Bad Gateway** error is displayed.

## 💡 Expected Behavior
The `bpkilint` container should automatically restart if stopped, maintaining service availability for Boulder and avoiding gateway errors in Nginx.

## 🚨 Actual Behavior
The `bpkilint` container remains stopped until manually restarted using:
```sh
docker start labca-bpkilint-1
```

## 🌍 Environment
- **LabCA Version:** Current `main` branch
- **Docker Version:** `24.0.5`
- **OS:** Debian 12
- **Browser:** N/A

## 🔧 Proposed Solution
Add a `restart` policy to the `bpkilint` service in the `docker-compose.yml` file:
```yaml
  bpkilint:
    image: ghcr.io/digicert/pkilint:v0.10.1
    networks:
      bouldernet:
        ipv4_address: 10.77.77.9
    command: "gunicorn -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:80 pkilint.rest:app"
    restart: always
```

## 📎 Additional Context
This issue was discovered while debugging a **502 Bad Gateway** error caused by Boulder being unable to connect to `bpkilint` at `bpkilint:80`. The Boulder container (`labca-boulder-1`) was stuck in a restarting state until `bpkilint` was manually restarted.

Additionally, the Boulder logs were filled with the repeating error message:
```
still trying to connect to bpkilint:80
```
This information may help other users identify the root cause more easily when encountering similar issues.

Thank you for considering this enhancement!
